import type { Goal } from '../core/types';

export const DEFAULT_GOALS: Goal[] = [
  {
    id: 'goal-q1-revenue',
    title: 'Q1 Revenue Target',
    description: 'Grow recurring revenue through new retainer clients and upsells.',
    motivation: 'Financial stability lets me invest in better tools and hire help.',
    category: 'professional',
    status: 'active',
    priority: 'high',
    color: '#2563EB',
    progressType: 'milestone',
    progressValue: 50,
    keyResults: [
      { id: 'kr-1', title: 'New retainer clients', current: 3, target: 5, unit: 'clients' },
      { id: 'kr-2', title: 'Monthly recurring revenue', current: 8200, target: 12000, unit: '$' },
    ],
    milestones: [
      {
        id: 'ms-clients',
        title: '5 new retainer clients',
        targetType: 'number',
        startValue: 0,
        targetValue: 5,
        currentValue: 3,
        unit: 'clients',
        dueDate: '2026-03-31',
        status: 'pending',
        order: 0,
      },
      {
        id: 'ms-pipeline',
        title: 'Pipeline review complete',
        targetType: 'boolean',
        dueDate: '2026-02-15',
        status: 'completed',
        completedAt: '2026-02-10T10:00:00.000Z',
        order: 1,
      },
      {
        id: 'ms-mrr',
        title: 'Monthly recurring revenue',
        targetType: 'currency',
        startValue: 0,
        targetValue: 12000,
        currentValue: 8200,
        dueDate: '2026-03-31',
        status: 'pending',
        order: 2,
      },
    ],
    startDate: '2026-01-01T00:00:00.000Z',
    targetDate: '2026-03-31',
    reviewFrequency: 'weekly',
    tags: ['revenue', 'q1'],
    checkIns: [
      {
        id: 'ci-1',
        date: '2026-02-10T10:00:00.000Z',
        note: 'Closed 2 new retainers this week. Pipeline looking strong.',
        progressSnapshot: 50,
        mood: 'good',
      },
      {
        id: 'ci-2',
        date: '2026-01-20T14:00:00.000Z',
        note: 'Started outreach campaign. 12 warm leads in pipeline.',
        progressSnapshot: 25,
        mood: 'ok',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-02-10T10:00:00.000Z',
  },
  {
    id: 'goal-product-launch',
    title: 'Product Launch',
    description: 'Ship v1 of the mobile app with core features and beta feedback loop.',
    motivation: 'Launching proves the concept and unlocks the next funding round.',
    category: 'professional',
    status: 'active',
    priority: 'high',
    color: '#7C3AED',
    progressType: 'milestone',
    progressValue: 25,
    keyResults: [
      { id: 'kr-3', title: 'Beta testers onboarded', current: 15, target: 50, unit: 'users' },
      { id: 'kr-4', title: 'Core features complete', current: 3, target: 8, unit: 'features' },
    ],
    milestones: [
      {
        id: 'ms-wireframes',
        title: 'Wireframes approved',
        targetType: 'boolean',
        dueDate: '2026-03-15',
        status: 'completed',
        completedAt: '2026-03-01T09:00:00.000Z',
        order: 0,
      },
      {
        id: 'ms-beta',
        title: 'Beta release',
        targetType: 'tasks',
        taskTarget: 12,
        taskCompleted: 4,
        dueDate: '2026-04-30',
        status: 'pending',
        order: 1,
      },
      {
        id: 'ms-launch',
        title: 'Public launch',
        targetType: 'boolean',
        dueDate: '2026-06-01',
        status: 'pending',
        order: 2,
      },
      {
        id: 'ms-marketing',
        title: 'Marketing campaign live',
        targetType: 'boolean',
        dueDate: '2026-05-15',
        status: 'pending',
        order: 3,
      },
    ],
    startDate: '2026-01-15T00:00:00.000Z',
    targetDate: '2026-06-01',
    reviewFrequency: 'biweekly',
    tags: ['product', 'launch'],
    checkIns: [
      {
        id: 'ci-3',
        date: '2026-03-01T09:00:00.000Z',
        note: 'Wireframes signed off. Engineering sprint started.',
        progressSnapshot: 25,
        mood: 'great',
      },
    ],
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'goal-design-system',
    title: 'Design System Maturity',
    description: 'Build a cohesive component library with documentation and adoption metrics.',
    motivation: 'Consistency saves hours every week and makes our work look professional.',
    category: 'professional',
    status: 'active',
    priority: 'medium',
    color: '#0891B2',
    progressType: 'percentage',
    progressValue: 65,
    keyResults: [
      { id: 'kr-5', title: 'Components documented', current: 26, target: 40, unit: 'components' },
      { id: 'kr-6', title: 'Team adoption rate', current: 70, target: 90, unit: '%' },
    ],
    milestones: [
      {
        id: 'ms-audit',
        title: 'Component audit complete',
        targetType: 'boolean',
        dueDate: '2026-01-20',
        status: 'completed',
        completedAt: '2026-01-18T16:00:00.000Z',
        order: 0,
      },
      {
        id: 'ms-tokens',
        title: 'Design tokens finalized',
        targetType: 'boolean',
        dueDate: '2026-02-28',
        status: 'completed',
        completedAt: '2026-02-25T11:00:00.000Z',
        order: 1,
      },
      {
        id: 'ms-storybook',
        title: 'Components documented',
        targetType: 'number',
        startValue: 0,
        targetValue: 40,
        currentValue: 26,
        unit: 'components',
        dueDate: '2026-04-01',
        status: 'pending',
        order: 2,
      },
    ],
    startDate: '2026-01-01T00:00:00.000Z',
    targetDate: '2026-04-30',
    reviewFrequency: 'monthly',
    tags: ['design', 'system'],
    checkIns: [
      {
        id: 'ci-4',
        date: '2026-02-25T11:00:00.000Z',
        note: 'Tokens shipped. Team feedback very positive.',
        progressSnapshot: 65,
        mood: 'good',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-02-25T11:00:00.000Z',
  },
  {
    id: 'goal-fitness',
    title: 'Run a Half Marathon',
    description: 'Train consistently and complete a half marathon by end of summer.',
    motivation: 'Proving I can commit to something hard outside of work.',
    category: 'health',
    status: 'active',
    priority: 'medium',
    color: '#16A34A',
    progressType: 'numeric',
    progressValue: 30,
    keyResults: [
      { id: 'kr-7', title: 'Weekly mileage', current: 12, target: 25, unit: 'miles/wk' },
      { id: 'kr-8', title: 'Long run distance', current: 6, target: 13, unit: 'miles' },
    ],
    milestones: [
      {
        id: 'ms-5k',
        title: 'Complete 5K race',
        targetType: 'boolean',
        dueDate: '2026-04-01',
        status: 'pending',
        order: 0,
      },
      {
        id: 'ms-10k',
        title: 'Complete 10K race',
        targetType: 'boolean',
        dueDate: '2026-05-15',
        status: 'pending',
        order: 1,
      },
      {
        id: 'ms-half',
        title: 'Weekly mileage target',
        targetType: 'number',
        startValue: 0,
        targetValue: 25,
        currentValue: 12,
        unit: 'miles/wk',
        dueDate: '2026-08-30',
        status: 'pending',
        order: 2,
      },
    ],
    startDate: '2026-02-01T00:00:00.000Z',
    targetDate: '2026-08-30',
    reviewFrequency: 'weekly',
    tags: ['fitness', 'personal'],
    checkIns: [
      {
        id: 'ci-5',
        date: '2026-03-01T07:00:00.000Z',
        note: 'Hit 12 miles this week. Knee feeling good.',
        progressSnapshot: 30,
        mood: 'good',
      },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-03-01T07:00:00.000Z',
  },
];

/** Export goals in KanbanEntity shape for KanbanProvider integration. */
export function goalsToKanbanEntities(goals: Goal[]) {
  return goals.map((g) => ({
    id: g.id,
    label: g.title,
    color: g.color,
    subtitle: `${CATEGORY_LABELS[g.category]} · ${g.status}`,
  }));
}

export function milestonesToKanbanEntities(goals: Goal[]) {
  return goals.flatMap((g) =>
    g.milestones.map((m) => ({
      id: m.id,
      label: m.title,
      goalId: g.id,
      subtitle: m.dueDate ? `Due ${new Date(m.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}` : undefined,
    })),
  );
}

const CATEGORY_LABELS: Record<string, string> = {
  professional: 'Professional',
  personal: 'Personal',
  financial: 'Financial',
  health: 'Health',
  learning: 'Learning',
  other: 'Other',
};
